name: Execute SSH command on new commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Execute SSH command
        run: |
          ssh root@${{ secrets.REMOTE_HOST }} "cd /root/strikr-api && yarn build && yarn start"
